// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: admin.proto

package adminpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProxyAdmin_GetBackends_FullMethodName                     = "/admin.ProxyAdmin/GetBackends"
	ProxyAdmin_GetBackend_FullMethodName                      = "/admin.ProxyAdmin/GetBackend"
	ProxyAdmin_AddBackend_FullMethodName                      = "/admin.ProxyAdmin/AddBackend"
	ProxyAdmin_RemoveBackend_FullMethodName                   = "/admin.ProxyAdmin/RemoveBackend"
	ProxyAdmin_UpdateBackend_FullMethodName                   = "/admin.ProxyAdmin/UpdateBackend"
	ProxyAdmin_GetVirtualHosts_FullMethodName                 = "/admin.ProxyAdmin/GetVirtualHosts"
	ProxyAdmin_GetVirtualHost_FullMethodName                  = "/admin.ProxyAdmin/GetVirtualHost"
	ProxyAdmin_AddVirtualHost_FullMethodName                  = "/admin.ProxyAdmin/AddVirtualHost"
	ProxyAdmin_RemoveVirtualHost_FullMethodName               = "/admin.ProxyAdmin/RemoveVirtualHost"
	ProxyAdmin_UpdateVirtualHost_FullMethodName               = "/admin.ProxyAdmin/UpdateVirtualHost"
	ProxyAdmin_GetVirtualHostSecurityConfig_FullMethodName    = "/admin.ProxyAdmin/GetVirtualHostSecurityConfig"
	ProxyAdmin_UpdateVirtualHostSecurityConfig_FullMethodName = "/admin.ProxyAdmin/UpdateVirtualHostSecurityConfig"
	ProxyAdmin_GetGlobalConfig_FullMethodName                 = "/admin.ProxyAdmin/GetGlobalConfig"
	ProxyAdmin_SetGlobalConfig_FullMethodName                 = "/admin.ProxyAdmin/SetGlobalConfig"
	ProxyAdmin_GetMetrics_FullMethodName                      = "/admin.ProxyAdmin/GetMetrics"
)

// ProxyAdminClient is the client API for ProxyAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProxyAdminClient interface {
	// backends
	GetBackends(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetBackendsResponse, error)
	GetBackend(ctx context.Context, in *GetBackendRequest, opts ...grpc.CallOption) (*BackendResponse, error)
	AddBackend(ctx context.Context, in *AddBackendRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	RemoveBackend(ctx context.Context, in *RemoveBackendRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	UpdateBackend(ctx context.Context, in *UpdateBackendRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	// virtual hosts
	GetVirtualHosts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetVirtualHostsResponse, error)
	GetVirtualHost(ctx context.Context, in *GetVirtualHostRequest, opts ...grpc.CallOption) (*VirtualHost, error)
	AddVirtualHost(ctx context.Context, in *AddVirtualHostRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	RemoveVirtualHost(ctx context.Context, in *RemoveVirtualHostRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	UpdateVirtualHost(ctx context.Context, in *UpdateVirtualHostRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	GetVirtualHostSecurityConfig(ctx context.Context, in *GetVirtualHostRequest, opts ...grpc.CallOption) (*SecurityConfigResponse, error)
	UpdateVirtualHostSecurityConfig(ctx context.Context, in *UpdateSecurityConfigRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	// global
	GetGlobalConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GlobalConfig, error)
	SetGlobalConfig(ctx context.Context, in *GlobalConfig, opts ...grpc.CallOption) (*BasicResponse, error)
	// metrics
	GetMetrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MetricsResponse, error)
}

type proxyAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyAdminClient(cc grpc.ClientConnInterface) ProxyAdminClient {
	return &proxyAdminClient{cc}
}

func (c *proxyAdminClient) GetBackends(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetBackendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBackendsResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_GetBackends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) GetBackend(ctx context.Context, in *GetBackendRequest, opts ...grpc.CallOption) (*BackendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackendResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_GetBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) AddBackend(ctx context.Context, in *AddBackendRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_AddBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) RemoveBackend(ctx context.Context, in *RemoveBackendRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_RemoveBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) UpdateBackend(ctx context.Context, in *UpdateBackendRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_UpdateBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) GetVirtualHosts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetVirtualHostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVirtualHostsResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_GetVirtualHosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) GetVirtualHost(ctx context.Context, in *GetVirtualHostRequest, opts ...grpc.CallOption) (*VirtualHost, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VirtualHost)
	err := c.cc.Invoke(ctx, ProxyAdmin_GetVirtualHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) AddVirtualHost(ctx context.Context, in *AddVirtualHostRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_AddVirtualHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) RemoveVirtualHost(ctx context.Context, in *RemoveVirtualHostRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_RemoveVirtualHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) UpdateVirtualHost(ctx context.Context, in *UpdateVirtualHostRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_UpdateVirtualHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) GetVirtualHostSecurityConfig(ctx context.Context, in *GetVirtualHostRequest, opts ...grpc.CallOption) (*SecurityConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecurityConfigResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_GetVirtualHostSecurityConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) UpdateVirtualHostSecurityConfig(ctx context.Context, in *UpdateSecurityConfigRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_UpdateVirtualHostSecurityConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) GetGlobalConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GlobalConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GlobalConfig)
	err := c.cc.Invoke(ctx, ProxyAdmin_GetGlobalConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) SetGlobalConfig(ctx context.Context, in *GlobalConfig, opts ...grpc.CallOption) (*BasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_SetGlobalConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) GetMetrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyAdminServer is the server API for ProxyAdmin service.
// All implementations must embed UnimplementedProxyAdminServer
// for forward compatibility.
type ProxyAdminServer interface {
	// backends
	GetBackends(context.Context, *Empty) (*GetBackendsResponse, error)
	GetBackend(context.Context, *GetBackendRequest) (*BackendResponse, error)
	AddBackend(context.Context, *AddBackendRequest) (*BasicResponse, error)
	RemoveBackend(context.Context, *RemoveBackendRequest) (*BasicResponse, error)
	UpdateBackend(context.Context, *UpdateBackendRequest) (*BasicResponse, error)
	// virtual hosts
	GetVirtualHosts(context.Context, *Empty) (*GetVirtualHostsResponse, error)
	GetVirtualHost(context.Context, *GetVirtualHostRequest) (*VirtualHost, error)
	AddVirtualHost(context.Context, *AddVirtualHostRequest) (*BasicResponse, error)
	RemoveVirtualHost(context.Context, *RemoveVirtualHostRequest) (*BasicResponse, error)
	UpdateVirtualHost(context.Context, *UpdateVirtualHostRequest) (*BasicResponse, error)
	GetVirtualHostSecurityConfig(context.Context, *GetVirtualHostRequest) (*SecurityConfigResponse, error)
	UpdateVirtualHostSecurityConfig(context.Context, *UpdateSecurityConfigRequest) (*BasicResponse, error)
	// global
	GetGlobalConfig(context.Context, *Empty) (*GlobalConfig, error)
	SetGlobalConfig(context.Context, *GlobalConfig) (*BasicResponse, error)
	// metrics
	GetMetrics(context.Context, *Empty) (*MetricsResponse, error)
	mustEmbedUnimplementedProxyAdminServer()
}

// UnimplementedProxyAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProxyAdminServer struct{}

func (UnimplementedProxyAdminServer) GetBackends(context.Context, *Empty) (*GetBackendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBackends not implemented")
}
func (UnimplementedProxyAdminServer) GetBackend(context.Context, *GetBackendRequest) (*BackendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBackend not implemented")
}
func (UnimplementedProxyAdminServer) AddBackend(context.Context, *AddBackendRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBackend not implemented")
}
func (UnimplementedProxyAdminServer) RemoveBackend(context.Context, *RemoveBackendRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveBackend not implemented")
}
func (UnimplementedProxyAdminServer) UpdateBackend(context.Context, *UpdateBackendRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBackend not implemented")
}
func (UnimplementedProxyAdminServer) GetVirtualHosts(context.Context, *Empty) (*GetVirtualHostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVirtualHosts not implemented")
}
func (UnimplementedProxyAdminServer) GetVirtualHost(context.Context, *GetVirtualHostRequest) (*VirtualHost, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVirtualHost not implemented")
}
func (UnimplementedProxyAdminServer) AddVirtualHost(context.Context, *AddVirtualHostRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddVirtualHost not implemented")
}
func (UnimplementedProxyAdminServer) RemoveVirtualHost(context.Context, *RemoveVirtualHostRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveVirtualHost not implemented")
}
func (UnimplementedProxyAdminServer) UpdateVirtualHost(context.Context, *UpdateVirtualHostRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVirtualHost not implemented")
}
func (UnimplementedProxyAdminServer) GetVirtualHostSecurityConfig(context.Context, *GetVirtualHostRequest) (*SecurityConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVirtualHostSecurityConfig not implemented")
}
func (UnimplementedProxyAdminServer) UpdateVirtualHostSecurityConfig(context.Context, *UpdateSecurityConfigRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVirtualHostSecurityConfig not implemented")
}
func (UnimplementedProxyAdminServer) GetGlobalConfig(context.Context, *Empty) (*GlobalConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGlobalConfig not implemented")
}
func (UnimplementedProxyAdminServer) SetGlobalConfig(context.Context, *GlobalConfig) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGlobalConfig not implemented")
}
func (UnimplementedProxyAdminServer) GetMetrics(context.Context, *Empty) (*MetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedProxyAdminServer) mustEmbedUnimplementedProxyAdminServer() {}
func (UnimplementedProxyAdminServer) testEmbeddedByValue()                    {}

// UnsafeProxyAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyAdminServer will
// result in compilation errors.
type UnsafeProxyAdminServer interface {
	mustEmbedUnimplementedProxyAdminServer()
}

func RegisterProxyAdminServer(s grpc.ServiceRegistrar, srv ProxyAdminServer) {
	// If the following call pancis, it indicates UnimplementedProxyAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProxyAdmin_ServiceDesc, srv)
}

func _ProxyAdmin_GetBackends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).GetBackends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_GetBackends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).GetBackends(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_GetBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).GetBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_GetBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).GetBackend(ctx, req.(*GetBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_AddBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).AddBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_AddBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).AddBackend(ctx, req.(*AddBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_RemoveBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).RemoveBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_RemoveBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).RemoveBackend(ctx, req.(*RemoveBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_UpdateBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).UpdateBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_UpdateBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).UpdateBackend(ctx, req.(*UpdateBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_GetVirtualHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).GetVirtualHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_GetVirtualHosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).GetVirtualHosts(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_GetVirtualHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVirtualHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).GetVirtualHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_GetVirtualHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).GetVirtualHost(ctx, req.(*GetVirtualHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_AddVirtualHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVirtualHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).AddVirtualHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_AddVirtualHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).AddVirtualHost(ctx, req.(*AddVirtualHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_RemoveVirtualHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveVirtualHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).RemoveVirtualHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_RemoveVirtualHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).RemoveVirtualHost(ctx, req.(*RemoveVirtualHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_UpdateVirtualHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVirtualHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).UpdateVirtualHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_UpdateVirtualHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).UpdateVirtualHost(ctx, req.(*UpdateVirtualHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_GetVirtualHostSecurityConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVirtualHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).GetVirtualHostSecurityConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_GetVirtualHostSecurityConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).GetVirtualHostSecurityConfig(ctx, req.(*GetVirtualHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_UpdateVirtualHostSecurityConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSecurityConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).UpdateVirtualHostSecurityConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_UpdateVirtualHostSecurityConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).UpdateVirtualHostSecurityConfig(ctx, req.(*UpdateSecurityConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_GetGlobalConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).GetGlobalConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_GetGlobalConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).GetGlobalConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_SetGlobalConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GlobalConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).SetGlobalConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_SetGlobalConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).SetGlobalConfig(ctx, req.(*GlobalConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).GetMetrics(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ProxyAdmin_ServiceDesc is the grpc.ServiceDesc for ProxyAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProxyAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.ProxyAdmin",
	HandlerType: (*ProxyAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBackends",
			Handler:    _ProxyAdmin_GetBackends_Handler,
		},
		{
			MethodName: "GetBackend",
			Handler:    _ProxyAdmin_GetBackend_Handler,
		},
		{
			MethodName: "AddBackend",
			Handler:    _ProxyAdmin_AddBackend_Handler,
		},
		{
			MethodName: "RemoveBackend",
			Handler:    _ProxyAdmin_RemoveBackend_Handler,
		},
		{
			MethodName: "UpdateBackend",
			Handler:    _ProxyAdmin_UpdateBackend_Handler,
		},
		{
			MethodName: "GetVirtualHosts",
			Handler:    _ProxyAdmin_GetVirtualHosts_Handler,
		},
		{
			MethodName: "GetVirtualHost",
			Handler:    _ProxyAdmin_GetVirtualHost_Handler,
		},
		{
			MethodName: "AddVirtualHost",
			Handler:    _ProxyAdmin_AddVirtualHost_Handler,
		},
		{
			MethodName: "RemoveVirtualHost",
			Handler:    _ProxyAdmin_RemoveVirtualHost_Handler,
		},
		{
			MethodName: "UpdateVirtualHost",
			Handler:    _ProxyAdmin_UpdateVirtualHost_Handler,
		},
		{
			MethodName: "GetVirtualHostSecurityConfig",
			Handler:    _ProxyAdmin_GetVirtualHostSecurityConfig_Handler,
		},
		{
			MethodName: "UpdateVirtualHostSecurityConfig",
			Handler:    _ProxyAdmin_UpdateVirtualHostSecurityConfig_Handler,
		},
		{
			MethodName: "GetGlobalConfig",
			Handler:    _ProxyAdmin_GetGlobalConfig_Handler,
		},
		{
			MethodName: "SetGlobalConfig",
			Handler:    _ProxyAdmin_SetGlobalConfig_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _ProxyAdmin_GetMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
