// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: admin.proto

package adminpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProxyAdmin_GetBackends_FullMethodName                  = "/admin.ProxyAdmin/GetBackends"
	ProxyAdmin_GetBackend_FullMethodName                   = "/admin.ProxyAdmin/GetBackend"
	ProxyAdmin_AddBackend_FullMethodName                   = "/admin.ProxyAdmin/AddBackend"
	ProxyAdmin_RemoveBackend_FullMethodName                = "/admin.ProxyAdmin/RemoveBackend"
	ProxyAdmin_UpdateBackend_FullMethodName                = "/admin.ProxyAdmin/UpdateBackend"
	ProxyAdmin_GetVirtualHosts_FullMethodName              = "/admin.ProxyAdmin/GetVirtualHosts"
	ProxyAdmin_GetVirtualHost_FullMethodName               = "/admin.ProxyAdmin/GetVirtualHost"
	ProxyAdmin_GetVirtualHostSecurity_FullMethodName       = "/admin.ProxyAdmin/GetVirtualHostSecurity"
	ProxyAdmin_SetVirtualHostSecurityPolicy_FullMethodName = "/admin.ProxyAdmin/SetVirtualHostSecurityPolicy"
	ProxyAdmin_AddVirtualHost_FullMethodName               = "/admin.ProxyAdmin/AddVirtualHost"
	ProxyAdmin_RemoveVirtualHost_FullMethodName            = "/admin.ProxyAdmin/RemoveVirtualHost"
	ProxyAdmin_UpdateVirtualHost_FullMethodName            = "/admin.ProxyAdmin/UpdateVirtualHost"
	ProxyAdmin_GetServerConfig_FullMethodName              = "/admin.ProxyAdmin/GetServerConfig"
	ProxyAdmin_SetServerConfig_FullMethodName              = "/admin.ProxyAdmin/SetServerConfig"
	ProxyAdmin_GetLoadBalancer_FullMethodName              = "/admin.ProxyAdmin/GetLoadBalancer"
	ProxyAdmin_SetLoadBalancer_FullMethodName              = "/admin.ProxyAdmin/SetLoadBalancer"
	ProxyAdmin_GetPolicies_FullMethodName                  = "/admin.ProxyAdmin/GetPolicies"
	ProxyAdmin_UpsertPolicy_FullMethodName                 = "/admin.ProxyAdmin/UpsertPolicy"
	ProxyAdmin_GetMetrics_FullMethodName                   = "/admin.ProxyAdmin/GetMetrics"
)

// ProxyAdminClient is the client API for ProxyAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProxyAdminClient interface {
	// backends
	GetBackends(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetBackendsResponse, error)
	GetBackend(ctx context.Context, in *GetBackendRequest, opts ...grpc.CallOption) (*BackendResponse, error)
	AddBackend(ctx context.Context, in *AddBackendRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	RemoveBackend(ctx context.Context, in *RemoveBackendRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	UpdateBackend(ctx context.Context, in *UpdateBackendRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	// virtual hosts
	GetVirtualHosts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetVirtualHostsResponse, error)
	GetVirtualHost(ctx context.Context, in *GetVirtualHostRequest, opts ...grpc.CallOption) (*VirtualHost, error)
	GetVirtualHostSecurity(ctx context.Context, in *GetVirtualHostRequest, opts ...grpc.CallOption) (*VirtualHostSecurityResponse, error)
	SetVirtualHostSecurityPolicy(ctx context.Context, in *SetVirtualHostSecurityPolicyRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	AddVirtualHost(ctx context.Context, in *AddVirtualHostRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	RemoveVirtualHost(ctx context.Context, in *RemoveVirtualHostRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	UpdateVirtualHost(ctx context.Context, in *UpdateVirtualHostRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	// server
	GetServerConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerConfig, error)
	SetServerConfig(ctx context.Context, in *ServerConfig, opts ...grpc.CallOption) (*BasicResponse, error)
	// load balancer
	GetLoadBalancer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LoadBalancerConfig, error)
	SetLoadBalancer(ctx context.Context, in *LoadBalancerConfig, opts ...grpc.CallOption) (*BasicResponse, error)
	// security
	GetPolicies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetPoliciesResponse, error)
	UpsertPolicy(ctx context.Context, in *UpsertPolicyRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	// metrics
	GetMetrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MetricsResponse, error)
}

type proxyAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyAdminClient(cc grpc.ClientConnInterface) ProxyAdminClient {
	return &proxyAdminClient{cc}
}

func (c *proxyAdminClient) GetBackends(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetBackendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBackendsResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_GetBackends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) GetBackend(ctx context.Context, in *GetBackendRequest, opts ...grpc.CallOption) (*BackendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackendResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_GetBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) AddBackend(ctx context.Context, in *AddBackendRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_AddBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) RemoveBackend(ctx context.Context, in *RemoveBackendRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_RemoveBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) UpdateBackend(ctx context.Context, in *UpdateBackendRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_UpdateBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) GetVirtualHosts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetVirtualHostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVirtualHostsResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_GetVirtualHosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) GetVirtualHost(ctx context.Context, in *GetVirtualHostRequest, opts ...grpc.CallOption) (*VirtualHost, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VirtualHost)
	err := c.cc.Invoke(ctx, ProxyAdmin_GetVirtualHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) GetVirtualHostSecurity(ctx context.Context, in *GetVirtualHostRequest, opts ...grpc.CallOption) (*VirtualHostSecurityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VirtualHostSecurityResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_GetVirtualHostSecurity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) SetVirtualHostSecurityPolicy(ctx context.Context, in *SetVirtualHostSecurityPolicyRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_SetVirtualHostSecurityPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) AddVirtualHost(ctx context.Context, in *AddVirtualHostRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_AddVirtualHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) RemoveVirtualHost(ctx context.Context, in *RemoveVirtualHostRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_RemoveVirtualHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) UpdateVirtualHost(ctx context.Context, in *UpdateVirtualHostRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_UpdateVirtualHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) GetServerConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerConfig)
	err := c.cc.Invoke(ctx, ProxyAdmin_GetServerConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) SetServerConfig(ctx context.Context, in *ServerConfig, opts ...grpc.CallOption) (*BasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_SetServerConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) GetLoadBalancer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LoadBalancerConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadBalancerConfig)
	err := c.cc.Invoke(ctx, ProxyAdmin_GetLoadBalancer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) SetLoadBalancer(ctx context.Context, in *LoadBalancerConfig, opts ...grpc.CallOption) (*BasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_SetLoadBalancer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) GetPolicies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPoliciesResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_GetPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) UpsertPolicy(ctx context.Context, in *UpsertPolicyRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_UpsertPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) GetMetrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, ProxyAdmin_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyAdminServer is the server API for ProxyAdmin service.
// All implementations must embed UnimplementedProxyAdminServer
// for forward compatibility.
type ProxyAdminServer interface {
	// backends
	GetBackends(context.Context, *Empty) (*GetBackendsResponse, error)
	GetBackend(context.Context, *GetBackendRequest) (*BackendResponse, error)
	AddBackend(context.Context, *AddBackendRequest) (*BasicResponse, error)
	RemoveBackend(context.Context, *RemoveBackendRequest) (*BasicResponse, error)
	UpdateBackend(context.Context, *UpdateBackendRequest) (*BasicResponse, error)
	// virtual hosts
	GetVirtualHosts(context.Context, *Empty) (*GetVirtualHostsResponse, error)
	GetVirtualHost(context.Context, *GetVirtualHostRequest) (*VirtualHost, error)
	GetVirtualHostSecurity(context.Context, *GetVirtualHostRequest) (*VirtualHostSecurityResponse, error)
	SetVirtualHostSecurityPolicy(context.Context, *SetVirtualHostSecurityPolicyRequest) (*BasicResponse, error)
	AddVirtualHost(context.Context, *AddVirtualHostRequest) (*BasicResponse, error)
	RemoveVirtualHost(context.Context, *RemoveVirtualHostRequest) (*BasicResponse, error)
	UpdateVirtualHost(context.Context, *UpdateVirtualHostRequest) (*BasicResponse, error)
	// server
	GetServerConfig(context.Context, *Empty) (*ServerConfig, error)
	SetServerConfig(context.Context, *ServerConfig) (*BasicResponse, error)
	// load balancer
	GetLoadBalancer(context.Context, *Empty) (*LoadBalancerConfig, error)
	SetLoadBalancer(context.Context, *LoadBalancerConfig) (*BasicResponse, error)
	// security
	GetPolicies(context.Context, *Empty) (*GetPoliciesResponse, error)
	UpsertPolicy(context.Context, *UpsertPolicyRequest) (*BasicResponse, error)
	// metrics
	GetMetrics(context.Context, *Empty) (*MetricsResponse, error)
	mustEmbedUnimplementedProxyAdminServer()
}

// UnimplementedProxyAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProxyAdminServer struct{}

func (UnimplementedProxyAdminServer) GetBackends(context.Context, *Empty) (*GetBackendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBackends not implemented")
}
func (UnimplementedProxyAdminServer) GetBackend(context.Context, *GetBackendRequest) (*BackendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBackend not implemented")
}
func (UnimplementedProxyAdminServer) AddBackend(context.Context, *AddBackendRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBackend not implemented")
}
func (UnimplementedProxyAdminServer) RemoveBackend(context.Context, *RemoveBackendRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveBackend not implemented")
}
func (UnimplementedProxyAdminServer) UpdateBackend(context.Context, *UpdateBackendRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBackend not implemented")
}
func (UnimplementedProxyAdminServer) GetVirtualHosts(context.Context, *Empty) (*GetVirtualHostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVirtualHosts not implemented")
}
func (UnimplementedProxyAdminServer) GetVirtualHost(context.Context, *GetVirtualHostRequest) (*VirtualHost, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVirtualHost not implemented")
}
func (UnimplementedProxyAdminServer) GetVirtualHostSecurity(context.Context, *GetVirtualHostRequest) (*VirtualHostSecurityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVirtualHostSecurity not implemented")
}
func (UnimplementedProxyAdminServer) SetVirtualHostSecurityPolicy(context.Context, *SetVirtualHostSecurityPolicyRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVirtualHostSecurityPolicy not implemented")
}
func (UnimplementedProxyAdminServer) AddVirtualHost(context.Context, *AddVirtualHostRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddVirtualHost not implemented")
}
func (UnimplementedProxyAdminServer) RemoveVirtualHost(context.Context, *RemoveVirtualHostRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveVirtualHost not implemented")
}
func (UnimplementedProxyAdminServer) UpdateVirtualHost(context.Context, *UpdateVirtualHostRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVirtualHost not implemented")
}
func (UnimplementedProxyAdminServer) GetServerConfig(context.Context, *Empty) (*ServerConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerConfig not implemented")
}
func (UnimplementedProxyAdminServer) SetServerConfig(context.Context, *ServerConfig) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetServerConfig not implemented")
}
func (UnimplementedProxyAdminServer) GetLoadBalancer(context.Context, *Empty) (*LoadBalancerConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoadBalancer not implemented")
}
func (UnimplementedProxyAdminServer) SetLoadBalancer(context.Context, *LoadBalancerConfig) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLoadBalancer not implemented")
}
func (UnimplementedProxyAdminServer) GetPolicies(context.Context, *Empty) (*GetPoliciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPolicies not implemented")
}
func (UnimplementedProxyAdminServer) UpsertPolicy(context.Context, *UpsertPolicyRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertPolicy not implemented")
}
func (UnimplementedProxyAdminServer) GetMetrics(context.Context, *Empty) (*MetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedProxyAdminServer) mustEmbedUnimplementedProxyAdminServer() {}
func (UnimplementedProxyAdminServer) testEmbeddedByValue()                    {}

// UnsafeProxyAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyAdminServer will
// result in compilation errors.
type UnsafeProxyAdminServer interface {
	mustEmbedUnimplementedProxyAdminServer()
}

func RegisterProxyAdminServer(s grpc.ServiceRegistrar, srv ProxyAdminServer) {
	// If the following call pancis, it indicates UnimplementedProxyAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProxyAdmin_ServiceDesc, srv)
}

func _ProxyAdmin_GetBackends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).GetBackends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_GetBackends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).GetBackends(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_GetBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).GetBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_GetBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).GetBackend(ctx, req.(*GetBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_AddBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).AddBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_AddBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).AddBackend(ctx, req.(*AddBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_RemoveBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).RemoveBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_RemoveBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).RemoveBackend(ctx, req.(*RemoveBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_UpdateBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).UpdateBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_UpdateBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).UpdateBackend(ctx, req.(*UpdateBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_GetVirtualHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).GetVirtualHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_GetVirtualHosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).GetVirtualHosts(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_GetVirtualHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVirtualHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).GetVirtualHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_GetVirtualHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).GetVirtualHost(ctx, req.(*GetVirtualHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_GetVirtualHostSecurity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVirtualHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).GetVirtualHostSecurity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_GetVirtualHostSecurity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).GetVirtualHostSecurity(ctx, req.(*GetVirtualHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_SetVirtualHostSecurityPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVirtualHostSecurityPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).SetVirtualHostSecurityPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_SetVirtualHostSecurityPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).SetVirtualHostSecurityPolicy(ctx, req.(*SetVirtualHostSecurityPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_AddVirtualHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVirtualHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).AddVirtualHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_AddVirtualHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).AddVirtualHost(ctx, req.(*AddVirtualHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_RemoveVirtualHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveVirtualHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).RemoveVirtualHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_RemoveVirtualHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).RemoveVirtualHost(ctx, req.(*RemoveVirtualHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_UpdateVirtualHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVirtualHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).UpdateVirtualHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_UpdateVirtualHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).UpdateVirtualHost(ctx, req.(*UpdateVirtualHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_GetServerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).GetServerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_GetServerConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).GetServerConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_SetServerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).SetServerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_SetServerConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).SetServerConfig(ctx, req.(*ServerConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_GetLoadBalancer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).GetLoadBalancer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_GetLoadBalancer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).GetLoadBalancer(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_SetLoadBalancer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadBalancerConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).SetLoadBalancer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_SetLoadBalancer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).SetLoadBalancer(ctx, req.(*LoadBalancerConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_GetPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).GetPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_GetPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).GetPolicies(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_UpsertPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).UpsertPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_UpsertPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).UpsertPolicy(ctx, req.(*UpsertPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyAdmin_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).GetMetrics(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ProxyAdmin_ServiceDesc is the grpc.ServiceDesc for ProxyAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProxyAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.ProxyAdmin",
	HandlerType: (*ProxyAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBackends",
			Handler:    _ProxyAdmin_GetBackends_Handler,
		},
		{
			MethodName: "GetBackend",
			Handler:    _ProxyAdmin_GetBackend_Handler,
		},
		{
			MethodName: "AddBackend",
			Handler:    _ProxyAdmin_AddBackend_Handler,
		},
		{
			MethodName: "RemoveBackend",
			Handler:    _ProxyAdmin_RemoveBackend_Handler,
		},
		{
			MethodName: "UpdateBackend",
			Handler:    _ProxyAdmin_UpdateBackend_Handler,
		},
		{
			MethodName: "GetVirtualHosts",
			Handler:    _ProxyAdmin_GetVirtualHosts_Handler,
		},
		{
			MethodName: "GetVirtualHost",
			Handler:    _ProxyAdmin_GetVirtualHost_Handler,
		},
		{
			MethodName: "GetVirtualHostSecurity",
			Handler:    _ProxyAdmin_GetVirtualHostSecurity_Handler,
		},
		{
			MethodName: "SetVirtualHostSecurityPolicy",
			Handler:    _ProxyAdmin_SetVirtualHostSecurityPolicy_Handler,
		},
		{
			MethodName: "AddVirtualHost",
			Handler:    _ProxyAdmin_AddVirtualHost_Handler,
		},
		{
			MethodName: "RemoveVirtualHost",
			Handler:    _ProxyAdmin_RemoveVirtualHost_Handler,
		},
		{
			MethodName: "UpdateVirtualHost",
			Handler:    _ProxyAdmin_UpdateVirtualHost_Handler,
		},
		{
			MethodName: "GetServerConfig",
			Handler:    _ProxyAdmin_GetServerConfig_Handler,
		},
		{
			MethodName: "SetServerConfig",
			Handler:    _ProxyAdmin_SetServerConfig_Handler,
		},
		{
			MethodName: "GetLoadBalancer",
			Handler:    _ProxyAdmin_GetLoadBalancer_Handler,
		},
		{
			MethodName: "SetLoadBalancer",
			Handler:    _ProxyAdmin_SetLoadBalancer_Handler,
		},
		{
			MethodName: "GetPolicies",
			Handler:    _ProxyAdmin_GetPolicies_Handler,
		},
		{
			MethodName: "UpsertPolicy",
			Handler:    _ProxyAdmin_UpsertPolicy_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _ProxyAdmin_GetMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
