// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: admin.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

type BasicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicResponse) Reset() {
	*x = BasicResponse{}
	mi := &file_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicResponse) ProtoMessage() {}

func (x *BasicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicResponse.ProtoReflect.Descriptor instead.
func (*BasicResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{1}
}

func (x *BasicResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BasicResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BasicResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Backend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Weight        int32                  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backend) Reset() {
	*x = Backend{}
	mi := &file_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backend.ProtoReflect.Descriptor instead.
func (*Backend) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{2}
}

func (x *Backend) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Backend) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Backend) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type BackendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Weight        int32                  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	ErrorCount    uint32                 `protobuf:"varint,5,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	LastError     string                 `protobuf:"bytes,6,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendResponse) Reset() {
	*x = BackendResponse{}
	mi := &file_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendResponse) ProtoMessage() {}

func (x *BackendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendResponse.ProtoReflect.Descriptor instead.
func (*BackendResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{3}
}

func (x *BackendResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BackendResponse) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *BackendResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *BackendResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *BackendResponse) GetErrorCount() uint32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *BackendResponse) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type GetBackendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backends      []*BackendResponse     `protobuf:"bytes,1,rep,name=backends,proto3" json:"backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackendsResponse) Reset() {
	*x = GetBackendsResponse{}
	mi := &file_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackendsResponse) ProtoMessage() {}

func (x *GetBackendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackendsResponse.ProtoReflect.Descriptor instead.
func (*GetBackendsResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{4}
}

func (x *GetBackendsResponse) GetBackends() []*BackendResponse {
	if x != nil {
		return x.Backends
	}
	return nil
}

type GetBackendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackendRequest) Reset() {
	*x = GetBackendRequest{}
	mi := &file_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackendRequest) ProtoMessage() {}

func (x *GetBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackendRequest.ProtoReflect.Descriptor instead.
func (*GetBackendRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{5}
}

func (x *GetBackendRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AddBackendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Weight        int32                  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBackendRequest) Reset() {
	*x = AddBackendRequest{}
	mi := &file_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBackendRequest) ProtoMessage() {}

func (x *AddBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBackendRequest.ProtoReflect.Descriptor instead.
func (*AddBackendRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{6}
}

func (x *AddBackendRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AddBackendRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type RemoveBackendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBackendRequest) Reset() {
	*x = RemoveBackendRequest{}
	mi := &file_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBackendRequest) ProtoMessage() {}

func (x *RemoveBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBackendRequest.ProtoReflect.Descriptor instead.
func (*RemoveBackendRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveBackendRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UpdateBackendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Weight        int32                  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBackendRequest) Reset() {
	*x = UpdateBackendRequest{}
	mi := &file_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBackendRequest) ProtoMessage() {}

func (x *UpdateBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBackendRequest.ProtoReflect.Descriptor instead.
func (*UpdateBackendRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBackendRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpdateBackendRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *UpdateBackendRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type MetricsResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TotalRequests          uint64                 `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	FailedRequests         uint64                 `protobuf:"varint,2,opt,name=failed_requests,json=failedRequests,proto3" json:"failed_requests,omitempty"`
	AvgLatencyMs           float64                `protobuf:"fixed64,3,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	RequestsPerBackend     map[string]uint64      `protobuf:"bytes,4,rep,name=requests_per_backend,json=requestsPerBackend,proto3" json:"requests_per_backend,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	FailedPerBackend       map[string]uint64      `protobuf:"bytes,5,rep,name=failed_per_backend,json=failedPerBackend,proto3" json:"failed_per_backend,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	AvgLatencyPerBackend   map[string]float64     `protobuf:"bytes,6,rep,name=avg_latency_per_backend,json=avgLatencyPerBackend,proto3" json:"avg_latency_per_backend,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	ActiveConnections      map[string]uint64      `protobuf:"bytes,7,rep,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TimeoutsPerBackend     map[string]uint64      `protobuf:"bytes,8,rep,name=timeouts_per_backend,json=timeoutsPerBackend,proto3" json:"timeouts_per_backend,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	HealthChecksPerBackend map[string]uint64      `protobuf:"bytes,9,rep,name=health_checks_per_backend,json=healthChecksPerBackend,proto3" json:"health_checks_per_backend,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	FailedHealthChecks     map[string]uint64      `protobuf:"bytes,10,rep,name=failed_health_checks,json=failedHealthChecks,proto3" json:"failed_health_checks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	RateLimitBlocked       uint64                 `protobuf:"varint,11,opt,name=rate_limit_blocked,json=rateLimitBlocked,proto3" json:"rate_limit_blocked,omitempty"`
	RateLimitAllowed       uint64                 `protobuf:"varint,12,opt,name=rate_limit_allowed,json=rateLimitAllowed,proto3" json:"rate_limit_allowed,omitempty"`
	StatusCodes            map[int32]uint64       `protobuf:"bytes,13,rep,name=status_codes,json=statusCodes,proto3" json:"status_codes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	MethodsCount           map[string]uint64      `protobuf:"bytes,14,rep,name=methods_count,json=methodsCount,proto3" json:"methods_count,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	RequestSizeTotal       uint64                 `protobuf:"varint,15,opt,name=request_size_total,json=requestSizeTotal,proto3" json:"request_size_total,omitempty"`
	ResponseSizeTotal      uint64                 `protobuf:"varint,16,opt,name=response_size_total,json=responseSizeTotal,proto3" json:"response_size_total,omitempty"`
	Goroutines             uint64                 `protobuf:"varint,17,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	MemoryPercent          float32                `protobuf:"fixed32,18,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	CpuPercent             float32                `protobuf:"fixed32,19,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	Uptime                 string                 `protobuf:"bytes,20,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{9}
}

func (x *MetricsResponse) GetTotalRequests() uint64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *MetricsResponse) GetFailedRequests() uint64 {
	if x != nil {
		return x.FailedRequests
	}
	return 0
}

func (x *MetricsResponse) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *MetricsResponse) GetRequestsPerBackend() map[string]uint64 {
	if x != nil {
		return x.RequestsPerBackend
	}
	return nil
}

func (x *MetricsResponse) GetFailedPerBackend() map[string]uint64 {
	if x != nil {
		return x.FailedPerBackend
	}
	return nil
}

func (x *MetricsResponse) GetAvgLatencyPerBackend() map[string]float64 {
	if x != nil {
		return x.AvgLatencyPerBackend
	}
	return nil
}

func (x *MetricsResponse) GetActiveConnections() map[string]uint64 {
	if x != nil {
		return x.ActiveConnections
	}
	return nil
}

func (x *MetricsResponse) GetTimeoutsPerBackend() map[string]uint64 {
	if x != nil {
		return x.TimeoutsPerBackend
	}
	return nil
}

func (x *MetricsResponse) GetHealthChecksPerBackend() map[string]uint64 {
	if x != nil {
		return x.HealthChecksPerBackend
	}
	return nil
}

func (x *MetricsResponse) GetFailedHealthChecks() map[string]uint64 {
	if x != nil {
		return x.FailedHealthChecks
	}
	return nil
}

func (x *MetricsResponse) GetRateLimitBlocked() uint64 {
	if x != nil {
		return x.RateLimitBlocked
	}
	return 0
}

func (x *MetricsResponse) GetRateLimitAllowed() uint64 {
	if x != nil {
		return x.RateLimitAllowed
	}
	return 0
}

func (x *MetricsResponse) GetStatusCodes() map[int32]uint64 {
	if x != nil {
		return x.StatusCodes
	}
	return nil
}

func (x *MetricsResponse) GetMethodsCount() map[string]uint64 {
	if x != nil {
		return x.MethodsCount
	}
	return nil
}

func (x *MetricsResponse) GetRequestSizeTotal() uint64 {
	if x != nil {
		return x.RequestSizeTotal
	}
	return 0
}

func (x *MetricsResponse) GetResponseSizeTotal() uint64 {
	if x != nil {
		return x.ResponseSizeTotal
	}
	return 0
}

func (x *MetricsResponse) GetGoroutines() uint64 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

func (x *MetricsResponse) GetMemoryPercent() float32 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *MetricsResponse) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *MetricsResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

type GlobalConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyPort     int32                  `protobuf:"varint,1,opt,name=proxy_port,json=proxyPort,proto3" json:"proxy_port,omitempty"`
	LbStrategy    string                 `protobuf:"bytes,2,opt,name=lb_strategy,json=lbStrategy,proto3" json:"lb_strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalConfig) Reset() {
	*x = GlobalConfig{}
	mi := &file_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalConfig) ProtoMessage() {}

func (x *GlobalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalConfig.ProtoReflect.Descriptor instead.
func (*GlobalConfig) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{10}
}

func (x *GlobalConfig) GetProxyPort() int32 {
	if x != nil {
		return x.ProxyPort
	}
	return 0
}

func (x *GlobalConfig) GetLbStrategy() string {
	if x != nil {
		return x.LbStrategy
	}
	return ""
}

type SecurityConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RateLimiting  *RateLimitingConfig    `protobuf:"bytes,1,opt,name=rate_limiting,json=rateLimiting,proto3" json:"rate_limiting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityConfigResponse) Reset() {
	*x = SecurityConfigResponse{}
	mi := &file_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityConfigResponse) ProtoMessage() {}

func (x *SecurityConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityConfigResponse.ProtoReflect.Descriptor instead.
func (*SecurityConfigResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{11}
}

func (x *SecurityConfigResponse) GetRateLimiting() *RateLimitingConfig {
	if x != nil {
		return x.RateLimiting
	}
	return nil
}

type UpdateSecurityConfigRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Domain        string                  `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Config        *SecurityConfigResponse `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecurityConfigRequest) Reset() {
	*x = UpdateSecurityConfigRequest{}
	mi := &file_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecurityConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecurityConfigRequest) ProtoMessage() {}

func (x *UpdateSecurityConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecurityConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecurityConfigRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateSecurityConfigRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *UpdateSecurityConfigRequest) GetConfig() *SecurityConfigResponse {
	if x != nil {
		return x.Config
	}
	return nil
}

type RateLimitingConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	RatePerIp     int32                  `protobuf:"varint,2,opt,name=rate_per_ip,json=ratePerIp,proto3" json:"rate_per_ip,omitempty"`
	Burst         int32                  `protobuf:"varint,3,opt,name=burst,proto3" json:"burst,omitempty"`
	WindowSec     int32                  `protobuf:"varint,4,opt,name=window_sec,json=windowSec,proto3" json:"window_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitingConfig) Reset() {
	*x = RateLimitingConfig{}
	mi := &file_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitingConfig) ProtoMessage() {}

func (x *RateLimitingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitingConfig.ProtoReflect.Descriptor instead.
func (*RateLimitingConfig) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{13}
}

func (x *RateLimitingConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RateLimitingConfig) GetRatePerIp() int32 {
	if x != nil {
		return x.RatePerIp
	}
	return 0
}

func (x *RateLimitingConfig) GetBurst() int32 {
	if x != nil {
		return x.Burst
	}
	return 0
}

func (x *RateLimitingConfig) GetWindowSec() int32 {
	if x != nil {
		return x.WindowSec
	}
	return 0
}

type GetVirtualHostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VirtualHosts  []*VirtualHost         `protobuf:"bytes,1,rep,name=virtual_hosts,json=virtualHosts,proto3" json:"virtual_hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVirtualHostsResponse) Reset() {
	*x = GetVirtualHostsResponse{}
	mi := &file_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVirtualHostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVirtualHostsResponse) ProtoMessage() {}

func (x *GetVirtualHostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVirtualHostsResponse.ProtoReflect.Descriptor instead.
func (*GetVirtualHostsResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{14}
}

func (x *GetVirtualHostsResponse) GetVirtualHosts() []*VirtualHost {
	if x != nil {
		return x.VirtualHosts
	}
	return nil
}

type GetVirtualHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVirtualHostRequest) Reset() {
	*x = GetVirtualHostRequest{}
	mi := &file_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVirtualHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVirtualHostRequest) ProtoMessage() {}

func (x *GetVirtualHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVirtualHostRequest.ProtoReflect.Descriptor instead.
func (*GetVirtualHostRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{15}
}

func (x *GetVirtualHostRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type PathRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Backends      []string               `protobuf:"bytes,2,rep,name=backends,proto3" json:"backends,omitempty"`
	StripPrefix   bool                   `protobuf:"varint,3,opt,name=strip_prefix,json=stripPrefix,proto3" json:"strip_prefix,omitempty"`
	Rewrite       string                 `protobuf:"bytes,4,opt,name=rewrite,proto3" json:"rewrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathRoute) Reset() {
	*x = PathRoute{}
	mi := &file_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathRoute) ProtoMessage() {}

func (x *PathRoute) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathRoute.ProtoReflect.Descriptor instead.
func (*PathRoute) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{16}
}

func (x *PathRoute) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PathRoute) GetBackends() []string {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *PathRoute) GetStripPrefix() bool {
	if x != nil {
		return x.StripPrefix
	}
	return false
}

func (x *PathRoute) GetRewrite() string {
	if x != nil {
		return x.Rewrite
	}
	return ""
}

type VirtualHost struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Domain         string                  `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Backends       []string                `protobuf:"bytes,2,rep,name=backends,proto3" json:"backends,omitempty"`
	PathRoutes     []*PathRoute            `protobuf:"bytes,3,rep,name=path_routes,json=pathRoutes,proto3" json:"path_routes,omitempty"`
	SecurityConfig *SecurityConfigResponse `protobuf:"bytes,4,opt,name=security_config,json=securityConfig,proto3" json:"security_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VirtualHost) Reset() {
	*x = VirtualHost{}
	mi := &file_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualHost) ProtoMessage() {}

func (x *VirtualHost) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualHost.ProtoReflect.Descriptor instead.
func (*VirtualHost) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{17}
}

func (x *VirtualHost) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *VirtualHost) GetBackends() []string {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *VirtualHost) GetPathRoutes() []*PathRoute {
	if x != nil {
		return x.PathRoutes
	}
	return nil
}

func (x *VirtualHost) GetSecurityConfig() *SecurityConfigResponse {
	if x != nil {
		return x.SecurityConfig
	}
	return nil
}

type AddVirtualHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vhost         *VirtualHost           `protobuf:"bytes,1,opt,name=vhost,proto3" json:"vhost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVirtualHostRequest) Reset() {
	*x = AddVirtualHostRequest{}
	mi := &file_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVirtualHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVirtualHostRequest) ProtoMessage() {}

func (x *AddVirtualHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVirtualHostRequest.ProtoReflect.Descriptor instead.
func (*AddVirtualHostRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{18}
}

func (x *AddVirtualHostRequest) GetVhost() *VirtualHost {
	if x != nil {
		return x.Vhost
	}
	return nil
}

type RemoveVirtualHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveVirtualHostRequest) Reset() {
	*x = RemoveVirtualHostRequest{}
	mi := &file_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveVirtualHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVirtualHostRequest) ProtoMessage() {}

func (x *RemoveVirtualHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVirtualHostRequest.ProtoReflect.Descriptor instead.
func (*RemoveVirtualHostRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveVirtualHostRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type UpdateVirtualHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Vhost         *VirtualHost           `protobuf:"bytes,2,opt,name=vhost,proto3" json:"vhost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVirtualHostRequest) Reset() {
	*x = UpdateVirtualHostRequest{}
	mi := &file_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVirtualHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVirtualHostRequest) ProtoMessage() {}

func (x *UpdateVirtualHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVirtualHostRequest.ProtoReflect.Descriptor instead.
func (*UpdateVirtualHostRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateVirtualHostRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *UpdateVirtualHostRequest) GetVhost() *VirtualHost {
	if x != nil {
		return x.Vhost
	}
	return nil
}

var File_admin_proto protoreflect.FileDescriptor

const file_admin_proto_rawDesc = "" +
	"\n" +
	"\vadmin.proto\x12\x05admin\"\a\n" +
	"\x05Empty\"Y\n" +
	"\rBasicResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"M\n" +
	"\aBackend\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weight\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\"\xad\x01\n" +
	"\x0fBackendResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weight\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\x12\x1f\n" +
	"\verror_count\x18\x05 \x01(\rR\n" +
	"errorCount\x12\x1d\n" +
	"\n" +
	"last_error\x18\x06 \x01(\tR\tlastError\"I\n" +
	"\x13GetBackendsResponse\x122\n" +
	"\bbackends\x18\x01 \x03(\v2\x16.admin.BackendResponseR\bbackends\"%\n" +
	"\x11GetBackendRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"=\n" +
	"\x11AddBackendRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weight\"(\n" +
	"\x14RemoveBackendRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"Z\n" +
	"\x14UpdateBackendRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weight\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\"\x89\x0f\n" +
	"\x0fMetricsResponse\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x04R\rtotalRequests\x12'\n" +
	"\x0ffailed_requests\x18\x02 \x01(\x04R\x0efailedRequests\x12$\n" +
	"\x0eavg_latency_ms\x18\x03 \x01(\x01R\favgLatencyMs\x12`\n" +
	"\x14requests_per_backend\x18\x04 \x03(\v2..admin.MetricsResponse.RequestsPerBackendEntryR\x12requestsPerBackend\x12Z\n" +
	"\x12failed_per_backend\x18\x05 \x03(\v2,.admin.MetricsResponse.FailedPerBackendEntryR\x10failedPerBackend\x12g\n" +
	"\x17avg_latency_per_backend\x18\x06 \x03(\v20.admin.MetricsResponse.AvgLatencyPerBackendEntryR\x14avgLatencyPerBackend\x12\\\n" +
	"\x12active_connections\x18\a \x03(\v2-.admin.MetricsResponse.ActiveConnectionsEntryR\x11activeConnections\x12`\n" +
	"\x14timeouts_per_backend\x18\b \x03(\v2..admin.MetricsResponse.TimeoutsPerBackendEntryR\x12timeoutsPerBackend\x12m\n" +
	"\x19health_checks_per_backend\x18\t \x03(\v22.admin.MetricsResponse.HealthChecksPerBackendEntryR\x16healthChecksPerBackend\x12`\n" +
	"\x14failed_health_checks\x18\n" +
	" \x03(\v2..admin.MetricsResponse.FailedHealthChecksEntryR\x12failedHealthChecks\x12,\n" +
	"\x12rate_limit_blocked\x18\v \x01(\x04R\x10rateLimitBlocked\x12,\n" +
	"\x12rate_limit_allowed\x18\f \x01(\x04R\x10rateLimitAllowed\x12J\n" +
	"\fstatus_codes\x18\r \x03(\v2'.admin.MetricsResponse.StatusCodesEntryR\vstatusCodes\x12M\n" +
	"\rmethods_count\x18\x0e \x03(\v2(.admin.MetricsResponse.MethodsCountEntryR\fmethodsCount\x12,\n" +
	"\x12request_size_total\x18\x0f \x01(\x04R\x10requestSizeTotal\x12.\n" +
	"\x13response_size_total\x18\x10 \x01(\x04R\x11responseSizeTotal\x12\x1e\n" +
	"\n" +
	"goroutines\x18\x11 \x01(\x04R\n" +
	"goroutines\x12%\n" +
	"\x0ememory_percent\x18\x12 \x01(\x02R\rmemoryPercent\x12\x1f\n" +
	"\vcpu_percent\x18\x13 \x01(\x02R\n" +
	"cpuPercent\x12\x16\n" +
	"\x06uptime\x18\x14 \x01(\tR\x06uptime\x1aE\n" +
	"\x17RequestsPerBackendEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aC\n" +
	"\x15FailedPerBackendEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aG\n" +
	"\x19AvgLatencyPerBackendEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1aD\n" +
	"\x16ActiveConnectionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aE\n" +
	"\x17TimeoutsPerBackendEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aI\n" +
	"\x1bHealthChecksPerBackendEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aE\n" +
	"\x17FailedHealthChecksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1a>\n" +
	"\x10StatusCodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1a?\n" +
	"\x11MethodsCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"N\n" +
	"\fGlobalConfig\x12\x1d\n" +
	"\n" +
	"proxy_port\x18\x01 \x01(\x05R\tproxyPort\x12\x1f\n" +
	"\vlb_strategy\x18\x02 \x01(\tR\n" +
	"lbStrategy\"X\n" +
	"\x16SecurityConfigResponse\x12>\n" +
	"\rrate_limiting\x18\x01 \x01(\v2\x19.admin.RateLimitingConfigR\frateLimiting\"l\n" +
	"\x1bUpdateSecurityConfigRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x125\n" +
	"\x06config\x18\x02 \x01(\v2\x1d.admin.SecurityConfigResponseR\x06config\"\x83\x01\n" +
	"\x12RateLimitingConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1e\n" +
	"\vrate_per_ip\x18\x02 \x01(\x05R\tratePerIp\x12\x14\n" +
	"\x05burst\x18\x03 \x01(\x05R\x05burst\x12\x1d\n" +
	"\n" +
	"window_sec\x18\x04 \x01(\x05R\twindowSec\"R\n" +
	"\x17GetVirtualHostsResponse\x127\n" +
	"\rvirtual_hosts\x18\x01 \x03(\v2\x12.admin.VirtualHostR\fvirtualHosts\"/\n" +
	"\x15GetVirtualHostRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"x\n" +
	"\tPathRoute\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\bbackends\x18\x02 \x03(\tR\bbackends\x12!\n" +
	"\fstrip_prefix\x18\x03 \x01(\bR\vstripPrefix\x12\x18\n" +
	"\arewrite\x18\x04 \x01(\tR\arewrite\"\xbc\x01\n" +
	"\vVirtualHost\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1a\n" +
	"\bbackends\x18\x02 \x03(\tR\bbackends\x121\n" +
	"\vpath_routes\x18\x03 \x03(\v2\x10.admin.PathRouteR\n" +
	"pathRoutes\x12F\n" +
	"\x0fsecurity_config\x18\x04 \x01(\v2\x1d.admin.SecurityConfigResponseR\x0esecurityConfig\"A\n" +
	"\x15AddVirtualHostRequest\x12(\n" +
	"\x05vhost\x18\x01 \x01(\v2\x12.admin.VirtualHostR\x05vhost\"2\n" +
	"\x18RemoveVirtualHostRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"\\\n" +
	"\x18UpdateVirtualHostRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12(\n" +
	"\x05vhost\x18\x02 \x01(\v2\x12.admin.VirtualHostR\x05vhost2\x90\b\n" +
	"\n" +
	"ProxyAdmin\x127\n" +
	"\vGetBackends\x12\f.admin.Empty\x1a\x1a.admin.GetBackendsResponse\x12>\n" +
	"\n" +
	"GetBackend\x12\x18.admin.GetBackendRequest\x1a\x16.admin.BackendResponse\x12<\n" +
	"\n" +
	"AddBackend\x12\x18.admin.AddBackendRequest\x1a\x14.admin.BasicResponse\x12B\n" +
	"\rRemoveBackend\x12\x1b.admin.RemoveBackendRequest\x1a\x14.admin.BasicResponse\x12B\n" +
	"\rUpdateBackend\x12\x1b.admin.UpdateBackendRequest\x1a\x14.admin.BasicResponse\x12?\n" +
	"\x0fGetVirtualHosts\x12\f.admin.Empty\x1a\x1e.admin.GetVirtualHostsResponse\x12B\n" +
	"\x0eGetVirtualHost\x12\x1c.admin.GetVirtualHostRequest\x1a\x12.admin.VirtualHost\x12D\n" +
	"\x0eAddVirtualHost\x12\x1c.admin.AddVirtualHostRequest\x1a\x14.admin.BasicResponse\x12J\n" +
	"\x11RemoveVirtualHost\x12\x1f.admin.RemoveVirtualHostRequest\x1a\x14.admin.BasicResponse\x12J\n" +
	"\x11UpdateVirtualHost\x12\x1f.admin.UpdateVirtualHostRequest\x1a\x14.admin.BasicResponse\x12[\n" +
	"\x1cGetVirtualHostSecurityConfig\x12\x1c.admin.GetVirtualHostRequest\x1a\x1d.admin.SecurityConfigResponse\x12[\n" +
	"\x1fUpdateVirtualHostSecurityConfig\x12\".admin.UpdateSecurityConfigRequest\x1a\x14.admin.BasicResponse\x124\n" +
	"\x0fGetGlobalConfig\x12\f.admin.Empty\x1a\x13.admin.GlobalConfig\x12<\n" +
	"\x0fSetGlobalConfig\x12\x13.admin.GlobalConfig\x1a\x14.admin.BasicResponse\x122\n" +
	"\n" +
	"GetMetrics\x12\f.admin.Empty\x1a\x16.admin.MetricsResponseB\vZ\t./adminpbb\x06proto3"

var (
	file_admin_proto_rawDescOnce sync.Once
	file_admin_proto_rawDescData []byte
)

func file_admin_proto_rawDescGZIP() []byte {
	file_admin_proto_rawDescOnce.Do(func() {
		file_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)))
	})
	return file_admin_proto_rawDescData
}

var file_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_admin_proto_goTypes = []any{
	(*Empty)(nil),                       // 0: admin.Empty
	(*BasicResponse)(nil),               // 1: admin.BasicResponse
	(*Backend)(nil),                     // 2: admin.Backend
	(*BackendResponse)(nil),             // 3: admin.BackendResponse
	(*GetBackendsResponse)(nil),         // 4: admin.GetBackendsResponse
	(*GetBackendRequest)(nil),           // 5: admin.GetBackendRequest
	(*AddBackendRequest)(nil),           // 6: admin.AddBackendRequest
	(*RemoveBackendRequest)(nil),        // 7: admin.RemoveBackendRequest
	(*UpdateBackendRequest)(nil),        // 8: admin.UpdateBackendRequest
	(*MetricsResponse)(nil),             // 9: admin.MetricsResponse
	(*GlobalConfig)(nil),                // 10: admin.GlobalConfig
	(*SecurityConfigResponse)(nil),      // 11: admin.SecurityConfigResponse
	(*UpdateSecurityConfigRequest)(nil), // 12: admin.UpdateSecurityConfigRequest
	(*RateLimitingConfig)(nil),          // 13: admin.RateLimitingConfig
	(*GetVirtualHostsResponse)(nil),     // 14: admin.GetVirtualHostsResponse
	(*GetVirtualHostRequest)(nil),       // 15: admin.GetVirtualHostRequest
	(*PathRoute)(nil),                   // 16: admin.PathRoute
	(*VirtualHost)(nil),                 // 17: admin.VirtualHost
	(*AddVirtualHostRequest)(nil),       // 18: admin.AddVirtualHostRequest
	(*RemoveVirtualHostRequest)(nil),    // 19: admin.RemoveVirtualHostRequest
	(*UpdateVirtualHostRequest)(nil),    // 20: admin.UpdateVirtualHostRequest
	nil,                                 // 21: admin.MetricsResponse.RequestsPerBackendEntry
	nil,                                 // 22: admin.MetricsResponse.FailedPerBackendEntry
	nil,                                 // 23: admin.MetricsResponse.AvgLatencyPerBackendEntry
	nil,                                 // 24: admin.MetricsResponse.ActiveConnectionsEntry
	nil,                                 // 25: admin.MetricsResponse.TimeoutsPerBackendEntry
	nil,                                 // 26: admin.MetricsResponse.HealthChecksPerBackendEntry
	nil,                                 // 27: admin.MetricsResponse.FailedHealthChecksEntry
	nil,                                 // 28: admin.MetricsResponse.StatusCodesEntry
	nil,                                 // 29: admin.MetricsResponse.MethodsCountEntry
}
var file_admin_proto_depIdxs = []int32{
	3,  // 0: admin.GetBackendsResponse.backends:type_name -> admin.BackendResponse
	21, // 1: admin.MetricsResponse.requests_per_backend:type_name -> admin.MetricsResponse.RequestsPerBackendEntry
	22, // 2: admin.MetricsResponse.failed_per_backend:type_name -> admin.MetricsResponse.FailedPerBackendEntry
	23, // 3: admin.MetricsResponse.avg_latency_per_backend:type_name -> admin.MetricsResponse.AvgLatencyPerBackendEntry
	24, // 4: admin.MetricsResponse.active_connections:type_name -> admin.MetricsResponse.ActiveConnectionsEntry
	25, // 5: admin.MetricsResponse.timeouts_per_backend:type_name -> admin.MetricsResponse.TimeoutsPerBackendEntry
	26, // 6: admin.MetricsResponse.health_checks_per_backend:type_name -> admin.MetricsResponse.HealthChecksPerBackendEntry
	27, // 7: admin.MetricsResponse.failed_health_checks:type_name -> admin.MetricsResponse.FailedHealthChecksEntry
	28, // 8: admin.MetricsResponse.status_codes:type_name -> admin.MetricsResponse.StatusCodesEntry
	29, // 9: admin.MetricsResponse.methods_count:type_name -> admin.MetricsResponse.MethodsCountEntry
	13, // 10: admin.SecurityConfigResponse.rate_limiting:type_name -> admin.RateLimitingConfig
	11, // 11: admin.UpdateSecurityConfigRequest.config:type_name -> admin.SecurityConfigResponse
	17, // 12: admin.GetVirtualHostsResponse.virtual_hosts:type_name -> admin.VirtualHost
	16, // 13: admin.VirtualHost.path_routes:type_name -> admin.PathRoute
	11, // 14: admin.VirtualHost.security_config:type_name -> admin.SecurityConfigResponse
	17, // 15: admin.AddVirtualHostRequest.vhost:type_name -> admin.VirtualHost
	17, // 16: admin.UpdateVirtualHostRequest.vhost:type_name -> admin.VirtualHost
	0,  // 17: admin.ProxyAdmin.GetBackends:input_type -> admin.Empty
	5,  // 18: admin.ProxyAdmin.GetBackend:input_type -> admin.GetBackendRequest
	6,  // 19: admin.ProxyAdmin.AddBackend:input_type -> admin.AddBackendRequest
	7,  // 20: admin.ProxyAdmin.RemoveBackend:input_type -> admin.RemoveBackendRequest
	8,  // 21: admin.ProxyAdmin.UpdateBackend:input_type -> admin.UpdateBackendRequest
	0,  // 22: admin.ProxyAdmin.GetVirtualHosts:input_type -> admin.Empty
	15, // 23: admin.ProxyAdmin.GetVirtualHost:input_type -> admin.GetVirtualHostRequest
	18, // 24: admin.ProxyAdmin.AddVirtualHost:input_type -> admin.AddVirtualHostRequest
	19, // 25: admin.ProxyAdmin.RemoveVirtualHost:input_type -> admin.RemoveVirtualHostRequest
	20, // 26: admin.ProxyAdmin.UpdateVirtualHost:input_type -> admin.UpdateVirtualHostRequest
	15, // 27: admin.ProxyAdmin.GetVirtualHostSecurityConfig:input_type -> admin.GetVirtualHostRequest
	12, // 28: admin.ProxyAdmin.UpdateVirtualHostSecurityConfig:input_type -> admin.UpdateSecurityConfigRequest
	0,  // 29: admin.ProxyAdmin.GetGlobalConfig:input_type -> admin.Empty
	10, // 30: admin.ProxyAdmin.SetGlobalConfig:input_type -> admin.GlobalConfig
	0,  // 31: admin.ProxyAdmin.GetMetrics:input_type -> admin.Empty
	4,  // 32: admin.ProxyAdmin.GetBackends:output_type -> admin.GetBackendsResponse
	3,  // 33: admin.ProxyAdmin.GetBackend:output_type -> admin.BackendResponse
	1,  // 34: admin.ProxyAdmin.AddBackend:output_type -> admin.BasicResponse
	1,  // 35: admin.ProxyAdmin.RemoveBackend:output_type -> admin.BasicResponse
	1,  // 36: admin.ProxyAdmin.UpdateBackend:output_type -> admin.BasicResponse
	14, // 37: admin.ProxyAdmin.GetVirtualHosts:output_type -> admin.GetVirtualHostsResponse
	17, // 38: admin.ProxyAdmin.GetVirtualHost:output_type -> admin.VirtualHost
	1,  // 39: admin.ProxyAdmin.AddVirtualHost:output_type -> admin.BasicResponse
	1,  // 40: admin.ProxyAdmin.RemoveVirtualHost:output_type -> admin.BasicResponse
	1,  // 41: admin.ProxyAdmin.UpdateVirtualHost:output_type -> admin.BasicResponse
	11, // 42: admin.ProxyAdmin.GetVirtualHostSecurityConfig:output_type -> admin.SecurityConfigResponse
	1,  // 43: admin.ProxyAdmin.UpdateVirtualHostSecurityConfig:output_type -> admin.BasicResponse
	10, // 44: admin.ProxyAdmin.GetGlobalConfig:output_type -> admin.GlobalConfig
	1,  // 45: admin.ProxyAdmin.SetGlobalConfig:output_type -> admin.BasicResponse
	9,  // 46: admin.ProxyAdmin.GetMetrics:output_type -> admin.MetricsResponse
	32, // [32:47] is the sub-list for method output_type
	17, // [17:32] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_admin_proto_init() }
func file_admin_proto_init() {
	if File_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_proto_goTypes,
		DependencyIndexes: file_admin_proto_depIdxs,
		MessageInfos:      file_admin_proto_msgTypes,
	}.Build()
	File_admin_proto = out.File
	file_admin_proto_goTypes = nil
	file_admin_proto_depIdxs = nil
}
