global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'reverse-proxy'
    static_configs:
      - targets: ['reverse-proxy:8080']
    metrics_path: /metrics/prometheus